training_data: "./input/train_folds.csv"
test_data: "./input/test.csv"
model: "RandomForestClassifier"
fold: 0
fold_mapping:
  0: [1, 2, 3, 4]
  1: [0, 2, 3, 4]
  2: [0, 1, 3, 4]
  3: [0, 1, 2, 4]
  4: [0, 1, 2, 3]

